### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by alonsnir** [Polyconseil/zbarlight#22]
I suspect the problem is with my environment, but just in case raising it here
```
(venv)$ lsb_release -a
 No LSB modules are available.
 Distributor ID:	Ubuntu
 Description:	Ubuntu 14.04.5 LTS
 Release:	14.04
 Codename:	trusty

(venv) $ python --version
Python 2.7.12

(venv)$ pip --version
pip 10.0.1 from /home/ubuntu/www/venv/lib/python2.7/site-packages/pip (python 2.7)

(venv) $ pip install zbarlight
Collecting zbarlight
Installing collected packages: zbarlight
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/www/venv/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/ubuntu/www/venv/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/home/ubuntu/www/venv/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/ubuntu/www/venv/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 748, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/ubuntu/www/venv/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/ubuntu/www/venv/lib/python2.7/site-packages/pip/_internal/wheel.py", line 316, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: zbarlight .dist-info directory not found
```

**Comment by fbochu** [comment]
Thanks for the report, I manage to install Zbarlight on Ubuntu Trusty using the commands below. The only things that differ from your setup is the Python version (2.7.6 vs 2.7.12) and maybe the Setuptools version. Zbarlight requires Setuptools >= 30.3, could you check that this requirement is meet ?

```
(host) $ docker run --rm -ti ubuntu:14.04  # run an instance of Ubuntu Trusty

(ubuntu) # apt install python python-dev libzbar-dev python-virtualenv
(ubuntu) # adduser --disabled-password --gecos ",,," zb
(ubuntu) # su -l zb
(ubuntu) $ virtualenv venv
(ubuntu) $ . ./venv/bin/activate

(venv) $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

(venv) $ python --version
Python 2.7.6

(venv) $ pip --version
pip 1.5.4 from /home/zb/venv/local/lib/python2.7/site-packages (python 2.7)

(venv) $ pip install -U pip
(venv) $ pip --version
pip 10.0.1 from /home/zb/venv/local/lib/python2.7/site-packages/pip (python 2.7)

(venv) $ pip show setuptools | grep Version
Version: 2.2

(venv) $ pip install -U setuptools
(venv) $ pip show setuptools | grep Version
Version: 39.1.0

(venv) $ pip install zbarlight
(venv) $ pip show zbarlight
Name: zbarlight
Version: 2.0
Summary: A simple zbar wrapper
Home-page: https://github.com/Polyconseil/zbarlight
Author: Polyconseil
Author-email: opensource+zbarlight@polyconseil.fr
License: BSD 3-Clause License
Location: /home/zb2/venv/lib/python2.7/site-packages
Requires: Pillow
Required-by: 
```

**Comment by alonsnir** [comment]
Unfortunately it's not on docker so not sure what in my environment got 'polluted'.
```
(venv) $ pip show setuptools | grep Version

Version: 39.1.0
```
